# Generated by Django 2.2.5 on 2020-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_examples', '0003_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.IntegerField(choices=[(0, 'Mr'), (1, 'Mrs'), (2, 'Miss')], null=True),
        ),
    ]
