# Generated by Django 2.2.5 on 2021-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_examples', '0005_auto_20210115_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dissolved',
            field=models.BooleanField(default=False),
        ),
    ]
