# Generated by Django 3.2.7 on 2021-11-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_examples', '0008_tally'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tally',
            options={'verbose_name_plural': 'Tallies'},
        ),
    ]
