# Generated by Django 3.2.7 on 2021-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_examples', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='direct_tag',
            field=models.ManyToManyField(blank=True, to='datatable_examples.TagsDirect'),
        ),
    ]
