# Generated by Django 5.0.4 on 2025-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datatables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstate',
            name='column_order',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='savedstate',
            name='column_visibility',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='savedstate',
            name='view_class',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
