# Generated by Django 5.0.4 on 2025-07-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datatables', '0002_savedstate_column_order_savedstate_column_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstate',
            name='state',
            field=models.CharField(max_length=32768),
        ),
    ]
