# Generated by Django 5.0.4 on 2025-10-09 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datatables', '0003_alter_savedstate_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstate',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public/Private'),
        ),
        migrations.AlterField(
            model_name='savedstate',
            name='state',
            field=models.CharField(blank=True, max_length=32768, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='savedstate',
            unique_together={('table_id', 'view_class', 'name', 'user')},
        ),
    ]
